import React, { useState, useEffect, useRef } from 'react';
import { supabase } from '../lib/supabaseClient';
import { IndianRupee, ShieldCheck, Zap } from 'lucide-react';
import { getImportMappingProfiles, saveImportMappingProfile } from '../lib/importJobs';
const MembershipPage = () => { const [plans, setPlans] = useState([]);
const [loading, setLoading] = useState(true);
const [fetchError, setFetchError] = useState(null);
const [saving, setSaving] = useState(false);
const [message, setMessage] = useState(null);
const [legacyPlanInput, setLegacyPlanInput] = useState('');
const [planMappings, setPlanMappings] = useState({});
const [mappingProfiles, setMappingProfiles] = useState([]);
const [selectedProfileId, setSelectedProfileId] = useState('');
const [mappingSaving, setMappingSaving] = useState(false);
const [mappingMessage, setMappingMessage] = useState(null);
const timeoutRef = useRef(null);
useEffect(() => { fetchPlans();
fetchMembershipMappingProfiles();
return () => { if (timeoutRef.current) clearTimeout(timeoutRef.current);
};
}, []);
const normalizeMappingToken = (value) => String(value || '') .toLowerCase() .replace(/[^a-z0-9\s]/g, ' ') .replace(/\s+/g, ' ') .trim();
const getSuggestedPlan = (legacyName) => { const normalizedLegacy = normalizeMappingToken(legacyName);
const legacyTokens = normalizedLegacy.split(' ').filter(Boolean);
if (legacyTokens.length === 0) return plans[0]?.duration_type || '';
let bestPlan = plans[0]?.duration_type || '';
let bestScore = -1;
plans.forEach((plan) => { const candidate = String(plan.duration_type || '');
const normalizedCandidate = normalizeMappingToken(candidate);
const candidateTokens = normalizedCandidate.split(' ').filter(Boolean);
const overlapCount = candidateTokens.filter((token) => legacyTokens.includes(token)).length;
const startsWithBonus = normalizedLegacy.startsWith(normalizedCandidate) ? 1 : 0;
const score = overlapCount + startsWithBonus;
if (score > bestScore) { bestScore = score;
bestPlan = candidate;
} });
return bestPlan;
};
const fetchMembershipMappingProfiles = async () => { try { const { data: { user } } = await supabase.auth.getUser();
if (!user) return;
const profiles = await getImportMappingProfiles({ gymId: user.id, importType: 'memberships', });
setMappingProfiles(profiles);
if (profiles.length > 0) { setSelectedProfileId(String(profiles[0].id));
} } catch (error) { console.error('Error loading mapping profiles:', error);
} };
const fetchPlans = async () => { setLoading(true);
setFetchError(null);
const { data, error } = await supabase .from('membership_plans') .select('*') .order('price', { ascending: true });
if (error) { console.error('Error fetching plans:', error);
setFetchError('Failed to load pricing plans. Please try again.');
} else { setPlans(data || []);
} setLoading(false);
};
const handlePriceChange = (id, newPrice) => { const parsedPrice = parseFloat(newPrice) || 0;
const safePrice = Math.max(0, parsedPrice);
setPlans(prevPlans => prevPlans.map(p => p.id === id ? { ...p, price: safePrice } : p));
};
const savePlan = async (plan) => { setSaving(true);
const { error } = await supabase .from('membership_plans') .update({ price: plan.price, updated_at: new Date().toISOString() }) .eq('id', plan.id);
if (error) { console.error('Error updating plan:', error);
if (timeoutRef.current) { clearTimeout(timeoutRef.current);
timeoutRef.current = null;
} setMessage({ type: 'error', text: 'Failed to update pricing.' });
} else { if (timeoutRef.current) { clearTimeout(timeoutRef.current);
} setMessage({ type: 'success', text: `${plan.duration_type} price updated to ₹${plan.price}.` });
timeoutRef.current = setTimeout(() => setMessage(null), 3000);
} setSaving(false);
};
const legacyPlanNames = legacyPlanInput .split(/\r?\n/) .map((name) => name.trim()) .filter(Boolean);
const unresolvedMappings = legacyPlanNames.filter((legacyName) => !planMappings[legacyName]);
const updateMapping = (legacyName, mappedPlan) => { setPlanMappings((prev) => ({ ...prev, [legacyName]: mappedPlan }));
};
const autoSuggestMappings = () => { const nextMappings = {};
legacyPlanNames.forEach((legacyName) => { nextMappings[legacyName] = planMappings[legacyName] || getSuggestedPlan(legacyName);
});
setPlanMappings(nextMappings);
};
const saveMappingProfile = async () => { if (legacyPlanNames.length === 0) { setMappingMessage({ type: 'error', text: 'Add at least one legacy plan name before saving a mapping profile.' });
return;
} if (unresolvedMappings.length > 0) { setMappingMessage({ type: 'error', text: `Resolve ${unresolvedMappings.length} plan mappings before saving.` });
return;
} setMappingSaving(true);
try { const { data: { user } } = await supabase.auth.getUser();
if (!user) throw new Error('User not authenticated');
const mappingJson = { generated_at: new Date().toISOString(), mappings: legacyPlanNames.map((legacyName) => ({ legacy_plan_name: legacyName, mapped_duration_type: planMappings[legacyName], })), };
await saveImportMappingProfile({ gymId: user.id, importType: 'memberships', mappingJson, });
setMappingMessage({ type: 'success', text: 'Membership mapping profile saved.' });
fetchMembershipMappingProfiles();
} catch (error) { setMappingMessage({ type: 'error', text: error.message || 'Failed to save mapping profile.' });
} finally { setMappingSaving(false);
} };
const loadSelectedProfile = () => { const selectedProfile = mappingProfiles.find((profile) => String(profile.id) === selectedProfileId);
if (!selectedProfile) return;
const mappings = selectedProfile.mapping_json?.mappings || [];
const importedNames = mappings.map((entry) => entry.legacy_plan_name).filter(Boolean);
const nextMap = {};
mappings.forEach((entry) => { if (entry.legacy_plan_name) { nextMap[entry.legacy_plan_name] = entry.mapped_duration_type || '';
} });
setLegacyPlanInput(importedNames.join('\n'));
setPlanMappings(nextMap);
setMappingMessage({ type: 'success', text: 'Mapping profile loaded.' });
};
return ( <div className="app-page membership-page p-10"> <header className="mb-12"> <p className="text-[10px] tracking-[0.3em] text-white/40 font-mono mb-2">Systems / Tier Management</p> <div className="flex justify-between items-end"> <div> <h1 className="text-4xl md:text-5xl font-medium tracking-tighter">Operational <span className="text-white/20">Pricing</span></h1> <p className="text-[10px] text-white/40 mt-2 font-mono tracking-widest">Global revenue configuration board</p> </div> </div> </header> {message && ( <div className={`mb-8 p-4 border text-[10px] tracking-widest font-mono ${ message.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500' : 'bg-red-500/10 border-red-500/20 text-red-500' }`}> {message.text} </div> )} {fetchError && ( <div className="mb-8 p-4 border bg-red-500/10 border-red-500/20 text-red-500 text-[10px] tracking-widest font-mono"> {fetchError} </div> )} {loading ? ( <div className="p-24 text-center"> <span className="text-[10px] tracking-[0.5em] text-white/20 animate-pulse font-mono font-medium">Synchronizing Pricing Tiers...</span> </div> ) : ( <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"> {plans.map((plan) => ( <div key={plan.id} className="bg-[#151921] border border-white/5 p-8 rounded-2xl shadow-2xl shadow-black/40 flex flex-col group hover:border-white/10 transition-all"> <div className="flex justify-between items-start mb-8"> <div className="w-10 h-10 bg-white/5 rounded-xl flex items-center justify-center text-white/40 group-hover:text-emerald-400 transition-colors"> <Zap size={20} /> </div> <div className="px-2 py-0.5 border border-white/10 rounded-sm text-[8px] font-mono text-white/40 tracking-widest"> Live </div> </div> <p className="text-[10px] tracking-[0.2em] text-white/40 font-mono mb-1">{plan.duration_type}</p> <h3 className="text-lg font-medium tracking-tight mb-8">Subscription Tier</h3> <div className="mt-auto space-y-6"> <div className="relative group"> <div className="absolute left-4 top-1/2 -translate-y-1/2 text-white/40 group-focus-within:text-emerald-400 transition-colors"> <IndianRupee size={16} /> </div> <input type="number" value={plan.price} onChange={(e) => handlePriceChange(plan.id, e.target.value)} className="w-full bg-white/5 border border-white/10 rounded-xl py-4 pl-12 pr-4 text-xl font-medium tracking-tight focus:outline-none focus:border-emerald-500/50 transition-all" /> </div> <button onClick={() => savePlan(plan)} disabled={saving} className="w-full bg-white text-black py-4 rounded-xl text-[10px] tracking-[0.3em] font-bold hover:bg-emerald-500 hover:text-black transition-all disabled:opacity-50" > Set Pricing </button> </div> </div> ))} </div> )} <div className="mt-12 p-8 bg-white/5 border border-white/10 rounded-2xl flex items-start gap-6"> <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400 shrink-0"> <ShieldCheck size={24} /> </div> <div> <h4 className="text-sm font-medium tracking-tight text-white mb-2 ">Pricing Stability Protocol</h4> <p className="text-[10px] text-white/40 leading-relaxed font-mono tracking-wide "> Changing these values will not affect existing subscriptions. New prices will apply to all applications and renewals submitted from this point forward. The "Revenue Analytics" ledger will automatically calculate income based on the price accurately recorded at the time of each subscription. </p> </div> </div> <div className="mt-12 p-8 bg-white/5 border border-white/10 rounded-2xl"> <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4 mb-6"> <div> <h4 className="text-sm font-medium tracking-tight text-white mb-2 ">Migration Plan Mapping</h4> <p className="text-[10px] text-white/40 leading-relaxed font-mono tracking-wide "> Map old plan names to active duration tiers before membership imports are finalized. </p> </div> <div className="flex flex-wrap gap-2"> <button type="button" onClick={autoSuggestMappings} className="px-4 py-2 border border-white/20 text-[10px] tracking-[0.2em] font-medium text-white" > Auto Suggest </button> <button type="button" onClick={saveMappingProfile} disabled={mappingSaving} className="px-4 py-2 bg-white text-black text-[10px] tracking-[0.2em] font-bold disabled:opacity-60" > {mappingSaving ? 'Saving...' : 'Save Profile'} </button> </div> </div> <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"> <div className="lg:col-span-1 space-y-3"> <label className="text-[10px] tracking-[0.2em] font-mono text-white/40">Legacy Plan Names</label> <textarea value={legacyPlanInput} onChange={(e) => setLegacyPlanInput(e.target.value)} rows={10} placeholder={'Gold Plan\n3 Month Pro\nYearly Elite'} className="w-full bg-white/5 border border-white/10 px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-white/30" /> <p className="text-[10px] text-white/40 font-mono tracking-[0.15em]"> {legacyPlanNames.length} plans detected </p> </div> <div className="lg:col-span-2 space-y-4"> {legacyPlanNames.length === 0 ? ( <p className="text-[10px] text-white/40 font-mono tracking-[0.15em]">Enter legacy plan names to start mapping.</p> ) : ( <div className="space-y-3 max-h-64 overflow-auto pr-1"> {legacyPlanNames.map((legacyName) => ( <div key={legacyName} className="grid grid-cols-1 md:grid-cols-2 gap-3 border border-white/10 p-3"> <p className="text-xs text-white/70 tracking-[0.1em]">{legacyName}</p> <select value={planMappings[legacyName] || ''} onChange={(e) => updateMapping(legacyName, e.target.value)} className="bg-white/5 border border-white/10 px-3 py-2 text-[10px] tracking-[0.12em] text-white" > <option value="" className="bg-[#0B0E14]">Select duration</option> {plans.map((plan) => ( <option key={plan.id} value={plan.duration_type} className="bg-[#0B0E14]"> {plan.duration_type} </option> ))} </select> </div> ))} </div> )} <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1"> <div className="border border-white/10 p-3"> <p className="text-[9px] tracking-[0.15em] text-white/30">Resolved Mappings</p> <p className="text-lg text-emerald-400 mt-1">{legacyPlanNames.length - unresolvedMappings.length}</p> </div> <div className="border border-white/10 p-3"> <p className="text-[9px] tracking-[0.15em] text-white/30">Unresolved</p> <p className="text-lg text-amber-400 mt-1">{unresolvedMappings.length}</p> </div> </div> <div className="border border-white/10 p-3"> <p className="text-[10px] tracking-[0.2em] font-mono text-white/40 mb-2">Saved Profiles</p> <div className="flex flex-col md:flex-row gap-3"> <select value={selectedProfileId} onChange={(e) => setSelectedProfileId(e.target.value)} className="flex-1 bg-white/5 border border-white/10 px-3 py-2 text-[10px] tracking-[0.12em] text-white" > {mappingProfiles.length === 0 && <option value="" className="bg-[#0B0E14]">No profiles saved yet</option>} {mappingProfiles.map((profile) => ( <option key={profile.id} value={profile.id} className="bg-[#0B0E14]"> {new Date(profile.created_at).toLocaleString()} </option> ))} </select> <button type="button" onClick={loadSelectedProfile} disabled={!selectedProfileId} className="px-4 py-2 border border-white/20 text-[10px] tracking-[0.2em] font-medium text-white disabled:opacity-40" > Load Profile </button> </div> </div> {mappingMessage && ( <div className={`p-3 border text-xs ${mappingMessage.type === 'success' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400' : 'border-red-500/30 bg-red-500/10 text-red-400'}`}> {mappingMessage.text} </div> )} </div> </div> </div> </div> );
};
export default MembershipPage;
