import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabaseClient';
import { Calendar, History, FileText, Activity, IndianRupee } from 'lucide-react';
const CustomerDetailsModal = ({ isOpen, onClose, customer }) => { const [history, setHistory] = useState([]);
const [loading, setLoading] = useState(true);
useEffect(() => { if (isOpen && customer) { fetchHistory();
} }, [isOpen, customer]);
useEffect(() => { const handleEsc = (event) => { if (event.key === 'Escape') { onClose();
} };
if (isOpen) { window.addEventListener('keydown', handleEsc);
} return () => { window.removeEventListener('keydown', handleEsc);
};
}, [isOpen, onClose]);
const fetchHistory = async () => { setLoading(true);
try { const { data, error } = await supabase .from('subscriptions') .select('*') .eq('customer_id', customer.id) .order('created_at', { ascending: false });
if (error) throw error;
setHistory(data || []);
} catch (err) { console.error('Error fetching history:', err);
} finally { setLoading(false);
} };
if (!isOpen || !customer) return null;
const joinDate = new Date(customer.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
const parsedEnd = customer.membership_end_date ? new Date(customer.membership_end_date) : null;
const end = parsedEnd && !Number.isNaN(parsedEnd.getTime()) ? parsedEnd : null;
const today = new Date();
today.setHours(0, 0, 0, 0);
const isActive = Boolean(end && end >= today);
const daysRemaining = end ? Math.ceil((end - today) / (1000 * 60 * 60 * 24)) : 0;
return ( <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-300" onClick={(e) => { if (e.target === e.currentTarget) onClose();
}} > <div className="bg-[#1A1A1A] border border-white/10 w-full max-w-2xl rounded-2xl shadow-2xl p-8 flex flex-col max-h-[90vh]"> <div className="flex justify-between items-start mb-8 border-b border-white/5 pb-6"> <div> <h2 className="text-2xl font-bold tracking-tight text-white mb-2">Member Analytics</h2> <div className="flex items-center gap-3"> <span className="text-[10px] tracking-widest text-white/40 font-mono"> ID: {customer.id.substring(0, 8)} </span> {isActive ? ( <span className="px-2 py-0.5 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-[10px] font-medium tracking-widest rounded"> Active </span> ) : ( <span className="px-2 py-0.5 bg-red-500/10 text-red-500 border border-red-500/20 text-[10px] font-medium tracking-widest rounded"> Expired </span> )} </div> </div> <button onClick={onClose} className="text-white/40 hover:text-white transition-colors text-[10px] tracking-widest font-mono bg-white/5 hover:bg-white/10 px-3 py-1.5 rounded" > Close [ESC] </button> </div> <div className="flex-1 overflow-y-auto pr-2 space-y-8 pb-4 custom-scrollbar"> {/* Quick Stats Grid */} <div className="grid grid-cols-2 md:grid-cols-3 gap-4"> <div className="bg-[#151921] border border-white/5 rounded-xl p-4 flex flex-col justify-center items-center text-center"> <Calendar className="w-5 h-5 text-emerald-400 mb-2" /> <span className="text-[9px] tracking-widest text-white/40 font-mono mb-1">Joined</span> <span className="text-xs font-bold text-white">{joinDate}</span> </div> <div className="bg-[#151921] border border-white/5 rounded-xl p-4 flex flex-col justify-center items-center text-center"> <Activity className="w-5 h-5 text-emerald-400 mb-2" /> <span className="text-[9px] tracking-widest text-white/40 font-mono mb-1">Status</span> <span className={`text-xs font-bold ${isActive ? 'text-emerald-400' : 'text-red-400'}`}> {isActive ? `${daysRemaining} Days Left` : 'Expired'} </span> </div> <div className="bg-[#151921] border border-white/5 rounded-xl p-4 flex flex-col justify-center items-center text-center"> <History className="w-5 h-5 text-emerald-400 mb-2" /> <span className="text-[9px] tracking-widest text-white/40 font-mono mb-1">Current Plan</span> <span className="text-xs font-bold text-white">{customer.membership_duration || 'N/A'}</span> </div> </div> {/* Membership History */} <div> <h3 className="text-[10px] font-mono tracking-widest text-white/60 mb-4 flex items-center gap-2"> <History className="w-4 h-4" /> Subscription Ledger </h3> <div className="bg-[#151921] border border-white/5 rounded-xl overflow-hidden"> {loading ? ( <div className="p-8 text-center text-[10px] tracking-widest text-white/40 font-mono animate-pulse"> Querying Ledger... </div> ) : history.length === 0 ? ( <div className="p-8 text-center bg-white/[0.02]"> <p className="text-[10px] tracking-widest text-white/40 font-mono mb-2">No historical records</p> <p className="text-xs text-white/20">Older subscriptions were not synced prior to the V3 analytics update. Newer renewals will appear here automatically.</p> </div> ) : ( <div className="divide-y divide-white/5"> {history.map((record) => ( <div key={record.id} className="p-4 flex items-center justify-between hover:bg-white/[0.02] transition-colors"> <div className="flex items-center gap-4"> <div className="w-8 h-8 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center"> <IndianRupee className="w-3 h-3" /> </div> <div> <p className="text-sm font-bold text-white tracking-tight">{record.plan_name}</p> <p className="text-[10px] text-white/40 font-mono">{new Date(record.created_at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}</p> </div> </div> <div className="text-right"> <p className="text-emerald-400 font-mono font-bold text-sm">₹{record.amount}</p> <p className="text-[8px] tracking-[0.2em] font-mono text-white/20 mt-1">Status: {record.status}</p> </div> </div> ))} </div> )} </div> </div> </div> </div> </div> );
};
export default CustomerDetailsModal;
