import React, { useEffect, useRef } from "react";
import PropTypes from "prop-types";

const OnboardingModal = ({ onStartSetup, onClose }) => {
  const modalRef = useRef(null);
  const actionButtonRef = useRef(null);
  const previousFocusRef = useRef(null);
  const titleId = "onboarding-heading";

  useEffect(() => {
    previousFocusRef.current = document.activeElement;
    actionButtonRef.current?.focus();

    const handleKeyDown = (event) => {
      if (event.key === "Escape") {
        if (typeof onClose === "function") {
          onClose();
        }
        return;
      }

      if (event.key !== "Tab") return;
      const focusable = modalRef.current?.querySelectorAll(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
      );
      if (!focusable || focusable.length === 0) return;
      const first = focusable[0];
      const last = focusable[focusable.length - 1];

      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      if (previousFocusRef.current?.focus) {
        previousFocusRef.current.focus();
      }
    };
  }, [onClose, onStartSetup]);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm px-3 animate-in fade-in duration-300"
      role="dialog"
      aria-modal="true"
      aria-labelledby={titleId}
    >
      <div
        ref={modalRef}
        className="bg-[#151921] border border-white/10 w-full max-w-lg shadow-2xl animate-in zoom-in-95 duration-300 overflow-hidden rounded-2xl p-8 flex flex-col items-center"
      >
        <h2 id={titleId} className="text-2xl font-bold text-white mb-2">
          Before you get started 👋
        </h2>
        <div className="text-white/80 text-sm mb-4 text-center max-w-md">
          <p>
            To unlock all features, we need a few details about your business. This only takes 2 minutes and you'll only do it once.
          </p>
          <p className="mt-3">You'll be setting up:</p>
          <ul className="list-disc list-inside text-white/60 text-xs mt-2 mb-2">
            <li>Your gym / business name and contact details</li>
            <li>Receipt header information (shown on all receipts you send)</li>
          </ul>
          <span className="block mt-2 text-white/60 text-xs">
            Why do we need this?
            <br />
            Every receipt, member record, and payment report generated by this app pulls from these settings. Without them, core features won't work correctly.
          </span>
        </div>
        <button
          type="button"
          ref={actionButtonRef}
          className="mt-2 px-5 py-2.5 bg-white text-black border border-white/10 rounded-xl text-xs tracking-[0.12em] dm-sans-light-008 font-medium whitespace-nowrap hover:bg-white/90 transition-colors"
          onClick={() => typeof onStartSetup === "function" && onStartSetup()}
        >
          Set up now
        </button>
      </div>
    </div>
  );
};

OnboardingModal.propTypes = {
  onStartSetup: PropTypes.func.isRequired,
  onClose: PropTypes.func,
};

OnboardingModal.defaultProps = {
  onClose: undefined,
};

export default OnboardingModal;
